import { Music2, ImageIcon } from "lucide-react";
import { createAdminClient } from "@/lib/supabase/admin";

export const metadata = { title: "Quiz content" };

export default async function AdminQuizPage() {
  const admin = createAdminClient();
  const { data: quiz } = await admin.from("quizzes").select("id,title,description,grade,subject,is_published,quiz_sections(id,title,instruction,section_type,position,audio_url,questions(id,position,prompt,question_type,image_url,audio_url,points,answer_keys(answer)))").order("created_at", { ascending: true }).limit(1).maybeSingle();
  if (!quiz) return <main className="shell py-8"><h1 className="text-3xl font-black">Quiz content</h1><div className="card muted mt-6 p-8">No quiz has been imported. Run the migration or <code>npm run import:quiz</code>.</div></main>;
  quiz.quiz_sections.sort((a, b) => a.position - b.position);
  return <main className="shell py-8"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-sm font-extrabold uppercase tracking-wider text-[#61738a]">Content inspection</p><h1 className="mt-1 text-3xl font-black">{quiz.title}</h1><p className="muted mt-2">{quiz.grade} · {quiz.subject} · {quiz.description}</p></div><span className={`badge ${quiz.is_published ? "bg-[#e8f7f0] text-[#246c53]" : "bg-[#fff0f1] text-[#9a3038]"}`}>{quiz.is_published ? "Published" : "Draft"}</span></div><div className="mt-7 space-y-6">{quiz.quiz_sections.map((section) => <section className="card overflow-hidden" key={section.id}><header className="border-b border-[#dce6ee] bg-[#f7fafc] p-5"><p className="text-xs font-extrabold uppercase tracking-wider text-[#61738a]">Part {section.position} · {section.section_type}</p><h2 className="mt-1 text-xl font-black">{section.title}</h2><p className="muted mt-1 text-sm">{section.instruction}</p>{section.audio_url && <p className="mt-2 flex items-center gap-2 text-xs font-bold text-[#245ea9]"><Music2 size={15} /> {section.audio_url}</p>}</header><ol className="divide-y divide-[#e1e8ee]">{section.questions.sort((a, b) => a.position - b.position).map((question) => { const key = Array.isArray(question.answer_keys) ? question.answer_keys[0] : question.answer_keys; return <li className="p-5" key={question.id}><div className="flex flex-wrap justify-between gap-3"><div><p className="text-xs font-bold text-[#61738a]">Question {question.position} · {question.question_type} · {question.points} point</p><p className="mt-1 font-extrabold">{question.prompt}</p></div><span className="badge bg-[#eef4fa] text-[#3f5e7d]">Answer: {JSON.stringify(key?.answer)}</span></div>{(question.image_url || question.audio_url) && <p className="muted mt-3 flex items-center gap-2 text-xs">{question.image_url ? <ImageIcon size={15} /> : <Music2 size={15} />}{question.image_url || question.audio_url}</p>}</li>; })}</ol></section>)}</div></main>;
}
